name: Node.js and React Project for `new-york-legal-landing` CI with Docker and SSDNode

on:
  push:
    branches:
      - "release/**"

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: aperrasolutions/new-york-legal-landing:latest

  build-and-deploy:
    needs: docker-setup
    runs-on: ubuntu-latest
    steps:
      - name: Executing SSH in SSDNODE
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSDNODE_HOST }}
          username: ${{ secrets.SSDNODE_USERNAME }}
          password: ${{ secrets.SSDNODE_PASSWORD }}
          script: |
            sudo docker stop new-york-legal-landing || true
            sudo docker rm new-york-legal-landing || true
            sudo docker image rm aperrasolutions/new-york-legal-landing:latest || true
            sudo docker run --name new-york-legal-landing -d -p 3045:3000 \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e SMTP_EMAIL=${{ secrets.SMTP_EMAIL }} \
              -e SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} \
              -e CALENDLY_URL=${{ secrets.CALENDLY_URL }} \
              aperrasolutions/new-york-legal-landing:latest